@startuml
!theme plain
skinparam rectangle {
    BackgroundColor<<part>> #FFFFFF
    BorderColor<<part>> #455A64
}
skinparam frame {
    BackgroundColor #FAFAFA
    BorderColor #263238
}

' ===== IBD =====
title Internal Block Diagram (IBD) — DMXConsole

frame "ibd [Block] DMXConsole" {
    rectangle "mcu\n:XIAORP2040" <<part>> as mcu {
        portout p_uart
        portout p_i2c
        portout p_adc_joy
        portout p_adc_btn
        portout p_gpio_enc
        portout p_pwr
    }

    rectangle "radio\n:XBeeS1" <<part>> as radio {
        portin p_uart_r
        portin p_pwr_r
    }

    rectangle "screen\n:SSD1306" <<part>> as screen {
        portin p_i2c_s
        portin p_pwr_s
    }

    rectangle "joy\n:Joystick3Axis" <<part>> as joy {
        portin p_adc_j
        portin p_pwr_j
    }

    rectangle "buttons\n:ButtonPanel" <<part>> as buttons {
        portin p_adc_b
        portin p_pwr_b
    }

    rectangle "encoder\n:EC11Encoder" <<part>> as encoder {
        portin p_quad_e
        portin p_pwr_e
    }

    ' Connecteurs
    p_uart --> p_uart_r : «UART»\nD6=TX / D7=RX · 9600 bauds
    p_i2c --> p_i2c_s : «I2C»\nD4=SDA / D5=SCL · 0x3C
    p_adc_joy --> p_adc_j : «ADC»\nA0–A2 · 16 bits
    p_adc_btn --> p_adc_b : «ADC»\nA3 · pont diviseur
    p_gpio_enc --> p_quad_e : «GPIO»\nD0/D1 · rotaryio
    p_pwr --> p_pwr_r : 3.3V / GND
    p_pwr --> p_pwr_s : 3.3V / GND
    p_pwr --> p_pwr_j : 3.3V / GND
    p_pwr --> p_pwr_b : 3.3V / GND
    p_pwr --> p_pwr_e : 3.3V / GND
}

@enduml
